[2024-08-26T06:59:06.354+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-26T06:59:06.356+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-26T06:59:06.358+0000] {logging_mixin.py:188} INFO - [2024-08-26T06:59:06.358+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-26T06:59:06.407+0000] {logging_mixin.py:188} INFO - [2024-08-26T06:59:06.404+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 2, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 7, in <module>
    SECRET = parser.get('api_keys', 'reddit_secret_key')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'api_keys'
[2024-08-26T06:59:06.408+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-26T06:59:06.446+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.098 seconds
[2024-08-26T06:59:36.877+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-26T06:59:36.878+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-26T06:59:36.880+0000] {logging_mixin.py:188} INFO - [2024-08-26T06:59:36.880+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-26T06:59:36.923+0000] {logging_mixin.py:188} INFO - [2024-08-26T06:59:36.921+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 2, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 7, in <module>
    SECRET = parser.get('api_keys', 'reddit_secret_key')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'api_keys'
[2024-08-26T06:59:36.923+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-26T06:59:36.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.068 seconds
[2024-08-26T07:00:07.377+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:00:07.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-26T07:00:07.379+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:00:07.379+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:00:07.419+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:00:07.417+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 2, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 7, in <module>
    SECRET = parser.get('api_keys', 'reddit_secret_key')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'api_keys'
[2024-08-26T07:00:07.419+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:00:07.434+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.062 seconds
[2024-08-26T07:00:37.844+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:00:37.845+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-26T07:00:37.847+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:00:37.847+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:00:37.886+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:00:37.884+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 2, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 7, in <module>
    SECRET = parser.get('api_keys', 'reddit_secret_key')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'api_keys'
[2024-08-26T07:00:37.886+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:00:37.898+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.062 seconds
[2024-08-26T07:01:08.370+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:01:08.371+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-26T07:01:08.373+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:01:08.373+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:01:08.411+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:01:08.409+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 2, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 7, in <module>
    SECRET = parser.get('api_keys', 'reddit_secret_key')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'api_keys'
[2024-08-26T07:01:08.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:01:08.422+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.060 seconds
[2024-08-26T07:01:38.853+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:01:38.855+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-26T07:01:38.857+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:01:38.857+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:01:38.897+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:01:38.896+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 2, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 7, in <module>
    SECRET = parser.get('api_keys', 'reddit_secret_key')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'api_keys'
[2024-08-26T07:01:38.897+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:01:38.908+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.062 seconds
[2024-08-26T07:02:09.398+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:02:09.398+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-26T07:02:09.400+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:02:09.400+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:02:09.441+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:02:09.439+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 2, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 7, in <module>
    SECRET = parser.get('api_keys', 'reddit_secret_key')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'api_keys'
[2024-08-26T07:02:09.441+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:02:09.452+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.062 seconds
[2024-08-26T07:02:39.894+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:02:39.895+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-26T07:02:39.898+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:02:39.897+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:02:39.943+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:02:39.941+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 2, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 7, in <module>
    SECRET = parser.get('api_keys', 'reddit_secret_key')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'api_keys'
[2024-08-26T07:02:39.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:02:39.961+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.074 seconds
[2024-08-26T07:03:10.302+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:03:10.304+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-26T07:03:10.306+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:03:10.305+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:03:10.346+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:03:10.344+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 2, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 7, in <module>
    SECRET = parser.get('api_keys', 'reddit_secret_key')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'api_keys'
[2024-08-26T07:03:10.346+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:03:10.356+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.060 seconds
[2024-08-26T07:03:40.758+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:03:40.762+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-26T07:03:40.764+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:03:40.764+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:03:40.804+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:03:40.803+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 2, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 7, in <module>
    SECRET = parser.get('api_keys', 'reddit_secret_key')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'api_keys'
[2024-08-26T07:03:40.805+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:03:40.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.069 seconds
[2024-08-26T07:04:11.197+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:04:11.198+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-26T07:04:11.200+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:04:11.200+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:04:11.239+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:04:11.238+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 2, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 7, in <module>
    SECRET = parser.get('api_keys', 'reddit_secret_key')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'api_keys'
[2024-08-26T07:04:11.240+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:04:11.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.062 seconds
[2024-08-26T07:04:41.603+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:04:41.603+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-26T07:04:41.605+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:04:41.604+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:04:41.630+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:04:41.629+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 2, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 7, in <module>
    SECRET = parser.get('api_keys', 'reddit_secret_key')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'api_keys'
[2024-08-26T07:04:41.631+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:04:41.642+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.043 seconds
[2024-08-26T07:05:12.034+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:05:12.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-26T07:05:12.037+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:05:12.037+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:05:12.075+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:05:12.073+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/configparser.py", line 789, in get
    value = d[option]
  File "/usr/local/lib/python3.9/collections/__init__.py", line 941, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/local/lib/python3.9/collections/__init__.py", line 933, in __missing__
    raise KeyError(key)
KeyError: 'database_user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 2, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 18, in <module>
    DATABASE_USER = parser.get('database', 'database_user')
  File "/usr/local/lib/python3.9/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'database_user' in section: 'database'
[2024-08-26T07:05:12.075+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:05:12.085+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.058 seconds
[2024-08-26T07:05:42.552+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:05:42.553+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-26T07:05:42.555+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:05:42.554+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:05:42.592+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:05:42.591+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/configparser.py", line 789, in get
    value = d[option]
  File "/usr/local/lib/python3.9/collections/__init__.py", line 941, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/local/lib/python3.9/collections/__init__.py", line 933, in __missing__
    raise KeyError(key)
KeyError: 'database_user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 2, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 18, in <module>
    DATABASE_USER = parser.get('database', 'database_user')
  File "/usr/local/lib/python3.9/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'database_user' in section: 'database'
[2024-08-26T07:05:42.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:05:42.604+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.059 seconds
[2024-08-26T07:06:13.029+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:06:13.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-26T07:06:13.033+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:06:13.032+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:06:13.073+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:06:13.071+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/configparser.py", line 789, in get
    value = d[option]
  File "/usr/local/lib/python3.9/collections/__init__.py", line 941, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/local/lib/python3.9/collections/__init__.py", line 933, in __missing__
    raise KeyError(key)
KeyError: 'database_user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 10, in <module>
    from pipelines.reddit_pipeline import reddit_pipeline
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 2, in <module>
    from utils.constants import CLIENT_ID, SECRET
  File "/opt/airflow/utils/constants.py", line 18, in <module>
    DATABASE_USER = parser.get('database', 'database_user')
  File "/usr/local/lib/python3.9/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'database_user' in section: 'database'
[2024-08-26T07:06:13.073+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:06:13.086+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.064 seconds
[2024-08-26T07:06:43.517+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:06:43.517+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-26T07:06:43.519+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:06:43.519+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:06:43.550+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:06:43.549+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 20, in <module>
    dag = DAG(
TypeError: __init__() got an unexpected keyword argument 'dafault_args'
[2024-08-26T07:06:43.550+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:06:43.561+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.050 seconds
[2024-08-26T07:07:14.015+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:07:14.015+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-26T07:07:14.016+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:07:14.016+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:07:14.072+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:07:14.071+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 20, in <module>
    dag = DAG(
TypeError: __init__() got an unexpected keyword argument 'dafault_args'
[2024-08-26T07:07:14.073+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:07:14.085+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.076 seconds
[2024-08-26T07:07:17.062+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:07:17.062+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-08-26T07:07:17.064+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:07:17.063+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:07:17.098+0000] {processor.py:840} INFO - DAG(s) 'elt_reddit_pipeline' retrieved from /opt/airflow/dags/reddit_dag.py
[2024-08-26T07:07:17.169+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:07:17.168+0000] {override.py:1858} INFO - Created Permission View: can read on DAG:elt_reddit_pipeline
[2024-08-26T07:07:17.174+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:07:17.174+0000] {override.py:1858} INFO - Created Permission View: can delete on DAG:elt_reddit_pipeline
[2024-08-26T07:07:17.178+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:07:17.178+0000] {override.py:1858} INFO - Created Permission View: can edit on DAG:elt_reddit_pipeline
[2024-08-26T07:07:17.179+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:07:17.179+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-08-26T07:07:17.184+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:07:17.184+0000] {dag.py:3111} INFO - Creating ORM DAG for elt_reddit_pipeline
[2024-08-26T07:07:17.190+0000] {logging_mixin.py:188} INFO - [2024-08-26T07:07:17.190+0000] {dag.py:3947} INFO - Setting next_dagrun for elt_reddit_pipeline to 2024-08-25 00:00:00+00:00, run_after=2024-08-26 00:00:00+00:00
[2024-08-26T07:07:17.202+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.144 seconds
